### ISSUE TITLE
Vendors Support?

### ISSUE THREAD

**Issue by blairanderson** [amzn/amazon-advertising-api-php-sdk#13]
This isn't really a question about the library directly, but more hoping your experience with the actual API would give you answers. 

I am having no problems with seller accounts, but the vendor profiles are not returning results in the API. 

To be clear:
i'd expect calls to `/profiles` to behave exactly the same no matter if the underlying account is vendor or seller. 

With seller accounts i'm seeing all profiles, with vendor accounts the profiles are showing empty

**Comment by dbrent-amazon** [comment]
Hello,

Sponsored Products for vendors is not currently supported by the Advertising API.

Brent

**Comment by blairanderson** [comment]
Thanks Brent.

**Comment by ianrussel** [comment]
hi @blairanderson , is there any other mysterious step not mentioned by amazon in oder to have a profile data in /profiles endpoint ? I have same problem, for me it return empty. I followed all the steps according to docs, and it works fine when using sandbox since I can create a profile and use its id as a scope to get its related data like campaigns. I already implemented the LWA in frontend and tested it with my potential customer, a real amazon seller. The LWA works fine, and it return customer information but none is related to profile id. I tried the LWA multiple times and call then /profiles endpoint but no luck . Please share the steps to have profiles return data. I can confirm my potential customer has campaigns because he give me access to his google data studio for confirmation .

Thanks,


Ian
